steps:
- script: |
    gzip -vk *_sent.csv *_recv.csv
    gzip -vk *_metrics.json
  displayName: Compress tx time metrics
  workingDirectory: build

# cimetrics related tasks: render and publish results for Pull Requests build
- script: ./cimetrics_env.sh python -m cimetrics.plot
  env:
    METRICS_MONGO_CONNECTION: $(METRICS_MONGO_CONNECTION)
  workingDirectory: build
  displayName: 'Plot cimetrics'
  condition: eq(variables['Build.Reason'], 'PullRequest')

- script: ./cimetrics_env.sh python -m cimetrics.github_pr
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
  displayName: 'Post cimetrics graphs as PR comment'
  workingDirectory: build
  condition: eq(variables['Build.Reason'], 'PullRequest')

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: _cimetrics
    artifactName: cimetrics
  displayName: 'Publish cimetrics graphs as build artifact'
  condition: eq(variables['Build.Reason'], 'PullRequest')
