parameters:
  cmake_args: ''

steps:
- task: CMake@1
  displayName: CMake
  inputs:
    cmakeArgs: '-GNinja -DTARGET=sgx .. ${{ parameters.cmake_args }}'

- script: cmake .. -L
  displayName: Print CMake config
  workingDirectory: build

- script: ninja
  displayName: Ninja
  workingDirectory: build
