parameters:
  cmake_args: ''
  ninja_args: ''

steps:
- script: |
    cat /proc/cpuinfo
  displayName: /proc/cpuinfo
  condition: succeededOrFailed()

- task: CMake@1
  displayName: CMake
  inputs:
    cmakeArgs: '-L -GNinja -DTARGET=sgx .. ${{ parameters.cmake_args }}'

- script: ninja ${{ parameters.ninja_args }}
  displayName: Ninja
  workingDirectory: build
